### PR TITLE
Added TypeScript typings

### PR DESCRIPTION
**Pull request by vojty**
Credit goes to @feimosi https://github.com/CezaryDanielNowak/React-dotdotdot/issues/40#issuecomment-422143988

### CODE REVIEW

**Comment by vojty** [comment]
@CezaryDanielNowak bump

**Comment by CezaryDanielNowak** [comment]
Hey, thanks :)

**Comment by vojty** [comment]
no probs, can we have a release as well? :)

**Comment by vojty** [comment]
@CezaryDanielNowak still waiting for that release :/

**Comment by CezaryDanielNowak** [comment]
Sorry for that, now it's published as 1.2.4

**Pull request merged**
